### PR TITLE
Tensor5d6d

### PR DESCRIPTION
**Pull request by M1ngXU**
Impl's should be already impl'ed, just added (PAINFULLY ARGHHHH) all the broadcast/reduce impls. Added `tensor6d`-feature since this adds about 80% compilation time (18s -> 33s) due to all the permutation macro expansion (6! = 720 functions?).

### CODE REVIEW

**Comment by M1ngXU** [comment]
hopefully i did not cause any merging issues ....

**Comment by M1ngXU** [comment]
is there actually the need to impl select?

**Comment by M1ngXU** [comment]
ok sorry for opening a PR that quickly, i just found another block of impls missening

**Comment by M1ngXU** [comment]
i *hope* that i did all the impls now

**Comment by coreylowman** [comment]
Wow omg this is awesome!!

> Added tensor6d-feature since this adds about 80% compilation time (18s -> 33s)

Is this compile times for tests/examples? I'm curious if this would increase compile times for an external dependency

**Comment by coreylowman** [comment]
**Really** appreciate the hard work with this - thanks to your investigation here the 5d6d permutations in the #304 are much more lightweight, and don't increase compile times as much! Without this PR I wouldn't have figured out how to make lightweight marker traits for all the shape stuff. Seriously thank you for this investigation!!

**Pull request closed without merging**
