### PR TITLE
Restructure repo to use workspaces

### PR DESCRIPTION
**Pull request by cBournhonesque**
We'd like to create procedural macros to help reduce the amount of boilerplate code in the repo: https://github.com/coreylowman/dfdx/issues/95

Procedural macros need to be in their own crate, so we would need to restructure the repo to make use of rust workspaces, similarly to what tokio is doing. https://github.com/tokio-rs/tokio

### CODE REVIEW

**Comment by cBournhonesque** [comment]
@coreylowman what do you think? I saw your comment in the issue that suggests using a root workspace
I like this setup because there's no need to add `--workspace` everytime.
+ some blog post was recommending it: https://matklad.github.io/2021/08/22/large-rust-workspaces.html

**Comment by coreylowman** [comment]
@cBournhonesque thanks for sharing that article, it's super useful. Let me think about this for a couple days. On one hand, being consistent with other rust repos & having a standard layout is really good. On the other hand, I don't have any plans *currently* to add any more crates (than this macros one) or organize dfdx as multiple crates. The root workspace seems much simpler to me, and I'm also not sure if dfdx falls under the same category of "large workspace" that rust-analyzer does.

**Comment by coreylowman** [comment]
@cBournhonesque let's just use virtual root workspace for now. This will make the diff easier to review, and I can always move to the more scalable structure later

**Comment by cBournhonesque** [comment]
Sg! will close this and open another PR

**Pull request closed without merging**
