### PR TITLE
[WIP] Adds rayon support to CPU

### PR DESCRIPTION
**Pull request by coreylowman**
Adds `"threaded"` feature, which enables rayon on CPU for most tensor operations.

TODOS:
- [ ] Add to batched matmul
- [ ] Add feature flag description
- [ ] Add to conv2d?

### CODE REVIEW

**Comment by M1ngXU** [comment]
i really need this 😅 (no cuda gpu anymore)
anything i can help you with and do you have an approx. ETA?

**Comment by M1ngXU** [comment]
i also have a laptop but with 8 cores; maybe we could add another feature to only parallize cpu-heavy stuff? so all those small speedups with lots of overhead will still be single-threaded (and faster)?

**Comment by coreylowman** [comment]
The 30 core machine is a VM that I used for GPU development haha.

It's definitely possible, we'd need to figure out a good threshold for it.

I'm curious what performance differences you see - can you run the `cargo bench --bench softmax` with and without the `-F threaded` and see what the difference is?

**Comment by M1ngXU** [comment]
ok sure, gotta set up everything first though :D

**Comment by M1ngXU** [comment]
hmm, threaded is about twice as slow (too) (500ms - 600ms vs 1300ms - 1500ms)

**Comment by coreylowman** [comment]
I'll have to look into rayon a bit more I think. Maybe we should be setting up our own threadpool instead of using the global one?

**Comment by coreylowman** [comment]
Oh, maybe we should be iterating over chunks of data (going off of comments in this thread https://www.reddit.com/r/rust/comments/5snkx4/using_rayon_to_parallelize_a_loop_makes_my/)?

**Comment by coreylowman** [comment]
What chunk size are you using? 8 seemed better on my machine, but still not as good as non-threaded.

I'm still trying to figure out what exactly the overhead rayon introduces is. If we know the overhead then we can try to reduce it

**Comment by M1ngXU** [comment]
i am using `(len() - 1) / std::thread::available_parallelism().unwrap().get() + 1`, so basically `len / available_parallelism` rounded up

**Comment by M1ngXU** [comment]
and i've seen that we actually call extra methods on the threaded impl (didn't check which ones). maybe they have overhead too?

**Comment by M1ngXU** [comment]
actually rust-analyzer always makes me go to the std::Iterator implementation if I follow the `for_each()` method (even though this should go to rayon) ...

**Comment by coreylowman** [comment]
Gonna close this since not actively working on it. May restart work on it in the future. Also linking to #186

**Pull request closed without merging**
