### PR TITLE
Fixed a misleading docstring.

### PR DESCRIPTION
**Pull request by M1ngXU**
Misleading docstring of Tensor::nans_to

### CODE REVIEW

**Review by coreylowman — APPROVED** [review]

**Comment by coreylowman** [comment]
Thanks for the change!

**Comment by M1ngXU** [comment]
@coreylowman I just checked the other modules and all of them have a numpy/tensorflow (or idk what) equivalent of the function. Maybe this was purposely done so?

**Comment by M1ngXU** [comment]
> @coreylowman I just checked the other modules and all of them have a numpy/tensorflow (or idk what) equivalent of the function. Maybe this was purposely done so?

though [this](https://github.com/coreylowman/dfdx/blob/d7037549c3df0e0507bbe2269e7aee0f974324ba/src/tensor_ops/impl_max_last.rs#L15) pretty much proves the opposite (I guess ?)

**Comment by coreylowman** [comment]
@M1ngXU Yeah I was trying to include equivalents for other languages, although its done a bit inconsistently as you are uncovering 😄

**Comment by M1ngXU** [comment]
> @M1ngXU Yeah I was trying to include equivalents for other languages, although its done a bit inconsistently as you are uncovering 😄

I think you know the other/your apis better than me, so will you make it consistently?

**Pull request merged**
